### ISSUE TITLE
Add class to paragraph

### ISSUE THREAD

**Issue by mcondarelli** [tiarno/plastex#111]
First of all: thanks for this project.

Second: I found a trivial typo in `plasTeX/Base/LaTeX/Characters.py`
in line 139 "guillmotleft" should be "guillemotleft".

Third (and real reason for this Issue): I need to somehow extend `plastex` to add some custom class to some paragraph to allow specific CSS customization.

I have in mind something like: `\mypara[myclass]{This is the paragraph content.}` which should be translated into something like: `<p class="myclass">This is the paragraph content.</p>`.
Is something like that already available, before I dive into non-trivial modifications?

I am currently using the Debian-packaged version of `plastex` which I *think* is tag `1.0.0` and, if I need to code something, it's unclear to me which is the right branch to start from (apparently it should be `python3`, but that does not work with python 3.7 I have on my Debian Sid distribution).
Any hint would be welcome.

If it matters: I am trying to convert a PDF-formatted book (novel, no fancy math or images, but lots of direct speech; I got errors trying to use `\usepackage{quotmark}` and in `/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty`) to XHTML to convert it further in ebook/mobi/azw format for electronic publishing.

**Comment by tiarno** [comment]
You're right, python 3.7 had a breaking change for plastex and we think we have a fix but have not fully tested it yet. 
The master branch works with python 2.x
The python3 branch works for python 3.x where x != 7. 
The fix/generator branch you may want to try with python3.7; if you do, please let us know how it goes.

Also, you can find a tutorial on how to add your own tags here
http://tiarno.github.io/plastex/tutorials/
It is not too difficult.

For unsupported packages like quotmark, you can create the functionality yourself, put it in a quotmark.py file that is in your PYTHONPATH, or create an empty quotmark.sty file in your TEXINPUTS path. It won't do anything but your doc should compile.
