### ISSUE TITLE
pip3 installs broken version of plastex still

### ISSUE THREAD

**Issue by pehrsoderman** [tiarno/plastex#112]
Running pip3 to install plastex gives a broken version. This seems to be a case of issue #86 which is still alive and kicking.

The old issue seems to be closed as won't-fix, due to Python3 support being being experimental at the time. These days python3 is the main branch, and it would be nice to be able to install plastex through pip3. It should be possible to publish both Python2 and Python3 versions through PyPI in parallel. May I request that it is reconsidered?

Here is a short log of what happens when trying to install plastex through pip3. Also note that pip claims to install plastex-1.0, but the version installed looks to be 0.9.1. Is that intentional?

```
pehrs@pehrs:~$ pip3 install plastex
Collecting plastex
  Downloading https://files.pythonhosted.org/packages/79/a2/6de4263ee45cdffe14ab11c79f89c5096fc9b454007e1e73c9031b0bff86/plasTeX-1.0.0.tgz (881kB)
    100% |████████████████████████████████| 890kB 1.3MB/s 
Building wheels for collected packages: plastex
  Running setup.py bdist_wheel for plastex ... done
  Stored in directory: /home/pehrs/.cache/pip/wheels/ae/f0/0c/33b04c8ce3c693753de506d9cd9b32fedbfd77b0dec807129a
Successfully built plastex
Installing collected packages: plastex
Successfully installed plastex-1.0
pehrs@pehrs:~$ plastex 
plasTeX version 0.9.1                  <- That's interesting... Why do I get 0.9.1 from a package named plastex-1.0?
<snip>
pehrs@pehrs:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import plasTeX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pehrs/.local/lib/python3.6/site-packages/plasTeX/__init__.py", line 217
    raise AttributeError, 'could not find attribute "title"'
                        ^
SyntaxError: invalid syntax
>>> 
```

**Comment by tiarno** [comment]
thanks, the package on pypi has been updated: https://pypi.org/project/plasTeX/
