### ISSUE TITLE
Looping over allChildNodes: match classes

### ISSUE THREAD

**Issue by tobiasschweizer** [tiarno/plastex#12]
Hi

I am making my first steps with plasTeX and have a question. When I parse a document and loop over all its nodes, I would like to match their types.

When I print the types of the nodes (`print type(node)`), I get a list of very different classes:

```
<class 'plasTeX.Base.LaTeX.Numbering.setcounter'>
<class 'plasTeX.Base.TeX.Primitives.par'>
<class 'plasTeX.Base.LaTeX.Sectioning.subsubsection'>
<class 'plasTeX.Base.TeX.Primitives.par'>
<class 'plasTeX.Base.LaTeX.Space.hspace'>
<class 'plasTeX.Base.TeX.Text.medskip'>
<class 'plasTeX.Base.TeX.Primitives.par'>
<class 'plasTeX.Base.LaTeX.Paragraphs.noindent'>
<class 'plasTeX.Base.TeX.Text.ControlSpace'>
<class 'plasTeX.Context.endnote'>
<class 'plasTeX.Base.TeX.Text.bgroup'>
<class 'plasTeX.Base.LaTeX.FontSelection.textit'>
<class 'plasTeX.Context.idx'>
<class 'plasTeX.Base.TeX.Text.bgroup'>
<class 'plasTeX.Base.LaTeX.FontSelection.textit'>
<class 'plasTeX.Context.idxb'>
<class 'plasTeX.Base.TeX.Text.bgroup'>
<class 'plasTeX.Base.LaTeX.Sentences.SmallSpace'>
<class 'plasTeX.Base.LaTeX.Sentences.SmallSpace'>
<class 'plasTeX.Context.idxb'>
<class 'plasTeX.Base.TeX.Text.bgroup'>
<class 'plasTeX.Base.LaTeX.Breaking.NewLine'>
<class 'plasTeX.Base.LaTeX.Math.math'>
```

When I want to use `isinstance`, how do I know the expression to check against? I figured that out for text nodes:

```
#!/usr/bin/env python

import plasTeX
from plasTeX.TeX import TeX

doc = TeX(file="myfile.tex")

parsed = doc.parse()

for node in parsed.allChildNodes:
    if (isinstance(node, plasTeX.DOM.Text)):
        print 'Textnode: ' + node
    else:
       print type(node)
    
```

But if I do the same thing for the class `plasTeX.Context.idx`, I get an error:

```
(isinstance(node, plasTeX.Context.idx)):
AttributeError: 'module' object has no attribute 'idx'
```

So  obviously the information I get from `type` is not the expression to check against in `isinstance`.

How can get the correct path?

**Comment by tiarno** [comment]
Thanks for the report. Could you attach your tex file? When I use sample2e.tex, I don't get any Context nodes. I'd like to reproduce your output so I can understand the problem better.

Oh, I see that it's not possible to attach text files to an issue--what about creating a gist and adding the link?

thanks.

**Comment by tobiasschweizer** [comment]
The `plasTeXContext.idx` class represents the LaTeX tag `\idx{indexname}` used to build an index at the end of a book for personnames etc.

Here, I can give you an example (test.tex):

```latex

\subsubsection{myexample}

This my test text that I write to a person \idx{personA} that developed a very important formula $AB$ 

```

This is my test script:

```
#!/usr/bin/env python

from plasTeX.TeX import TeX

letter = TeX(file="test.tex")

parsed = letter.parse()

for node in parsed.allChildNodes:
    print type(node)
```

Its output:

```
..
WARNING: unrecognized command/environment: idx
<class 'plasTeX.Base.LaTeX.Sectioning.subsubsection'>
<class 'plasTeX.Base.TeX.Primitives.par'>
<class 'plasTeX.DOM.Text'>
<class 'plasTeX.Context.idx'>
<class 'plasTeX.Base.TeX.Text.bgroup'>
<class 'plasTeX.DOM.Text'>
<class 'plasTeX.DOM.Text'>
<class 'plasTeX.Base.LaTeX.Math.math'>
<class 'plasTeX.DOM.Text'>
<class 'plasTeX.DOM.Text'>


```
 
What I want, is to process the different types of nodes individually (\idx for example always refers to a person, math contains formulas etc). So what I need is a kind of a switch-case statement.

Probably, I should traverse the document recursively with `childNodes` and accessing each node again with `childNodes` if it contains children itself (like for example a subsubsection).

Plase note that I have to process single .tex-files individually, but the rendering would be done by calling a main-file. I want to import the files in a db that is not based on LaTeX.

**Comment by tiarno** [comment]
I think that what you're seeing is an artifact of the idx command not being defined. Line 510 in Context.py has the definition I think we're looking for:

        # Didn't find it, so generate a new class
        if self.warnOnUnrecognized and not self.isMathMode:
            log.warning('unrecognized command/environment: %s', key)
        self[key] = newclass = new.classobj(str(key), (plasTeX.UnrecognizedMacro,), {})
        return newclass

So the class is generated on the fly. If you use this comparison:

    isinstance(node, plasTeX.UnrecognizedMacro)

it will return True. So I think you're doing the right thing but because that command was not defined, it threw an error. If you define the idx command, you'll get a set of classes that omit the Context and idx will belong to whatever class it was defined as (section, text, math, etc.).

**Comment by tobiasschweizer** [comment]
Thank you very much for your answer!

I can match the `idx` now (as an unknow macro), but how can I access its contents?

```
\idx{personA}
```

How do I know that it is an `idx` and how do I get `personA` (the value it contains)?

**Comment by tobiasschweizer** [comment]
Or how could I define the idx macro/command in order to process it individually?

**Comment by tiarno** [comment]
I think the tutorial will be useful: http://tiarno.github.io/plastex/tutorials/

Basically, you do three things:

1. Create a python file so plastex can parse the command, say 'idxtest.py':
 
        from plasTeX import Base
        class idx(Base.Command):
            args = 'text'

2. Create a template file so plastex can render it, say 'idxtest.zpts':

        name: idx
        <b tal:content="self/attributes/text"></b>


3. Set the XHTMLTEMPLATES environment variable to the directory containing your template files (the file in step 2):
 
        export XHTMLTEMPLATES="/your/dir/with/templates"

Then if you have the code `\idx{personA}` in your tex file, it will be parsed and rendered in bold in the output html. You can define a host of new commands this way, customizing the output in any way you like.

**Comment by tobiasschweizer** [comment]
Thank you very much for the quick reply, this very helpful. I will try this out!

**Comment by tobiasschweizer** [comment]
Actually, I do not want to render LaTeX in HTML. 

I just want to process the single elements individually:

```
\subsubsection{myexample}

This my test text that I write to a person \idx{personA} that developed a very important formula $AB$ 

```

So  what I am trying is:

```
#!/usr/bin/env python

import plasTeX
from plasTeX.TeX import TeX
from plasTeX import Base

class idx(Base.Command):
    args = 'text'

letter = TeX(file="L001-T_utf8.tex")

parsed = letter.parse()

for node in parsed.allChildNodes:
    if (isinstance(node, plasTeX.DOM.Text)):
        pass
    elif (isinstance(node, plasTeX.UnrecognizedMacro)):
        print node.source
    else:
        pass

```

So whenever a userdefined macro is found, its name is printed out to the console. **Now the only thing missing is its value:** `personA`. How do I have to call my class `idx` to get it?

**Comment by tiarno** [comment]
Using your initial code that printed the node type from `parsed.allChildNodes()`, you'll see the new class `idxtest.idx`.

        <class 'idxtest.idx'>

So that node has a dictionary, `attributes` which has key `text`. The corresponding value is of type `plasTeX.TeXFragment`. You can get its value with `node.attributes.get('text').textContent`, where `node` is the `idx` element.

A `TeXFragment` has methods you can find in the doc:
http://tiarno.github.io/plastex/plastex/sect0024.html

**Comment by tobiasschweizer** [comment]
Sorry, I still do not get it. I wrote you an email with my files and output, so you can reproduce it.

Thanks again!
