### ISSUE TITLE
Incorrect Parsing of \sqrt Command

### ISSUE THREAD

**Issue by mmerko** [tiarno/plastex#15]
I'm not sure if this is a legitimate issue, or if I simply am not setting up my config properly (I am new to LaTeX and plasTeX), but when I parse **\sqrt[3]{x}** it does not correctly associate the child elements '[3]' and '{x}' with the parent '\sqrt' element, instead they resolve as siblings within the document...

While poking around, I noticed in _plasTeX/Base/LaTeX/Math.py_ that the __sqrt__ class is defined twice:

```python
class sqrt(Command):
	args = '[ n ] self'
```

and

```python
class sqrt(Command):
	pass
```

and when I comment out the latter version of the class it seems like the document parses correctly. Is there a reason for the second class declaration?

**Comment by kesmit13** [comment]
This does look like an error.  I removed the definition that didn’t contain arguments.

Kevin D Smith
Kevin.Smith@octobergray.com
