### ISSUE TITLE
\endverbatim not matched in included files

### ISSUE THREAD

**Issue by mungerd** [tiarno/plastex#16]
This is the problem I discussed in #14.
The `\endverbatim` macro is not matched correctly when it is not in the main LaTeX file, but rather part of a file included with `\include{...}` from the main file.

For example, plasTeX correctly matches two distinct verbatim environments containing `Foo` and `Bar` in the following:
```latex
\documentclass{article}
\begin{document}
\verbatim
Foo
\endverbatim
\begin{verbatim}
Bar
\end{verbatim}
\end{document}
```
Howevever, if the main file includes `foo.tex`:
```latex
    \documentclass{article}
    \begin{document}
    \include{foo}
    \end{document}
```
and `foo.tex` contains:
```latex
\verbatim
Foo
\endverbatim
\begin{verbatim}
Bar
\end{verbatim}
```
plasTeX incorrectly matches
```
Foo
\endverbatim
\begin{verbatim}
Bar
```
as the content of a single verbatim environment.

I wasn't able to find why this happens.

**Comment by kesmit13** [comment]
I just made a change that should fix this issue.

**Comment by mungerd** [comment]
Thanks!
