### ISSUE TITLE
Parsing of unknown environments

### ISSUE THREAD

**Issue by Thibauth** [tiarno/plastex#20]
First of all, thanks a lot for plastex, I think this is a great piece of software! As I was playing with it, I came across the following behavior which I found surprising. When parsing the following document:
```latex
\documentclass{article}
\usepackage{amsthm}
\begin{document}
\begin{proof}
test
\end{proof}
\end{document}
```
the XML representation is the following:
```xml
<dom-document xmlns:plastex="http://plastex.sf.net/">
<documentclass id="a0000000001">
    <plastex:arg name="options"/>
    <plastex:arg name="name">article</plastex:arg>
</documentclass> <usepackage id="a0000000002">
    <plastex:arg name="options"/>
    <plastex:arg name="names">[u'amsthm']</plastex:arg>
</usepackage> <document id="a0000000003">
<par id="a0000000004">
<proof id="a0000000005"/> test <proof id="a0000000006"/> </par></document> </dom-document>
```
I understand that the `amsthm` package is not yet supported. But even if I get a warning that the `proof` environment is unknown, I don't understand why the default behavior shouldn't be to parse it as something like:
```xml
<proof id="a0000000005"> test </proof>
```
i.e., having the `proof` tag enclose the environment content, to follow the original structure of the LaTeX document more closely. This way, even if the environment is not supported, we would still get a chance to generate useful HTML code using a template.

Is there any reason to prefer the current XML representation for unknown environments?

**Comment by tiarno** [comment]
I don't know for sure, but my  guess is that it needs a definition for `\proof` and `\endproof` underneath. Since those do not exist, you get two self-closing elements rather than begin/end elements.

You can add the behavior you want by subclassing `proof` off of the Environment class.
