### ISSUE TITLE
Running on OSX

### ISSUE THREAD

**Issue by niklasp** [tiarno/plastex#24]
I have followed your [tutorial](https://tiarno.github.io/plastex/tutorials/) but I am getting an error when running `plastex testing.tex` (also I am in the correct directory).

```
plasTeX version 1.0
Traceback (most recent call last):
  File "/usr/local/bin/plastex", line 109, in <module>
    main(sys.argv)
  File "/usr/local/bin/plastex", line 36, in main
    tex = TeX(document, file=file)
  File "/Library/Python/2.7/site-packages/plasTeX/TeX.py", line 121, in __init__
    self.input(codecs.open(self.kpsewhich(file), 'r', encoding, 'replace'))
  File "/Library/Python/2.7/site-packages/plasTeX/TeX.py", line 1344, in kpsewhich
    raise OSError, 'Could not find any file named: %s' % name
OSError: Could not find any file named: testing.tex
```
Do you have any tips for solving this?

**Comment by tiarno** [comment]
I haven't seen this problem before--do you have a TEXINPUTS environment variable set? If you do, please post the value it's set to.

**Comment by tiarno** [comment]
Another thing that Kevin mentioned to me offline is that this can happen when `kpsewhich` is not installed or not in your path. So, make sure you have `kpsewhich` installed, it's in your path and the current directory is included in your `TEXINPUTS` environment variable.

I use plastex on a mac and haven't had the problem. Let me know if that works for you.
