### ISSUE TITLE
Jinja2 support ?

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#25]
Is there any interest in adding [Jinja2](http://jinja.pocoo.org/) template engine support?

This template engine is inspired by Django's template language hence easy to use for many people who like both python and html.

Actually I already added support for Jinja2 here, I'm really asking whether I should bother to set up a pull request.

**Comment by kesmit13** [comment]
Go ahead and set up a pull request.  We'll see what we can do.

**Comment by PatrickMassot** [comment]
Thanks. As I tested my code, I uncovered something that looks like a bug to me (but maybe I only misunderstood). In a template file containing several templates, I tried to use start with ``default-engine: jinja2`` to avoid typing ``engine: jinja2`` for every template. This almost works except for the very first template of the file which still defaults to ZPT.

In order to see this, you can edit ``plasTeX/Renderers/XHTML/Math.zpts`` and add as first line ``default-engine: string`` and run ``plastex --renderer=XHTML`` on a file containing only:
```tex
\documentclass{article}

\begin{document}
 $1 + 1 = 2$
\end{document}
```

As far as I understand you should get either an exception or ZPT attributes in the output (since the string engine doesn't get rid of them). But you won't (at least I don't, even on a vanilla plasTeX). Now if you change Maths.zpts so that the first template appearing (before math) is ``name: nothing`` then plasTeX will choke on the document because it will try to use the string engine on the math template, as expected.

**Comment by kesmit13** [comment]
I guess I'm wondering how you registered the jinja2 engine.  Normally, the default template type is set by the file extension.  So you would add a line like the following in the PageTemplate class in plasTeX/Renderers/PageTemplate/__init__.py.

self.registerEngine('jinja2', None, '.jinja2', jinjahtmltemplate)

**Comment by PatrickMassot** [comment]
I understand the default engine can be set by file extension but the current implementation still contradicts the documentation at [this line](https://github.com/tiarno/plastex/blob/master/Doc/renderers.tex#L611). Again this has nothing to do with my patch, you can reproduce the problem mixing only string and ZPT as explained in my previous comment.

By the way, I was unsure what kind of extension to choose because I feel those multi-template files are much more plasTeX files than something directly related to the template engine, especially since one can mix different engines in the same file. To me it would make more sense to have a single extension for all plasTeX template files and always use the ``default-engine`` or ``engine`` directives.

Anyway, I'll use a different extension for jinja default.

**Comment by PatrickMassot** [comment]
Interestingly enough, when trying to use file extension to set the default engine, the bug gets mirrored: only the first template in a multi-template file gets the correct engine.

This time I took the time to pdb-hunt the bug. If I understand correctly, the problem is in [these lines](https://github.com/tiarno/plastex/blob/53869cbfdb09a8b5536bb3b4b83375f99e7555bc/plasTeX/Renderers/PageTemplate/__init__.py#L490-L504). The ``defaults`` dict is initially empty and filled only by ``default-*`` directives in the file. After the first template is "compiled" by [this line](https://github.com/tiarno/plastex/blob/53869cbfdb09a8b5536bb3b4b83375f99e7555bc/plasTeX/Renderers/PageTemplate/__init__.py#L501), the ``options`` dict is reset and you loose the default engine information coming from the file extension.

I don't quite understand why the initial value of ``default`` is not ``options.copy()``. From a distance, it seems to make more sense. 

By the way, is there any documentation explaining how to run the test suite? This is a typical case where I'd like to experiment changing something that may have implications I don't understand. But I'm not a python expert and, if typing ``py.test`` in the project root folder does not work, then I'm lost.

**Comment by kesmit13** [comment]
Fixed.

**Comment by PatrickMassot** [comment]
@kesmit13 Commit cc57edef06a0bb4455fbcf84e2cd2194d22e63ad does seem to fix the default-engine directive bug, but not the second bug I mentioned: default engine determined by file extension is wiped out after the first template is parsed. I still thing [this line](https://github.com/tiarno/plastex/blob/cc57edef06a0bb4455fbcf84e2cd2194d22e63ad/plasTeX/Renderers/PageTemplate/__init__.py#L491) should be ``defaults = options.copy()`` or, at least, followed by: 
```
if 'engine' in options:
  defaults['engine'] = options['engine']
```

**Comment by kesmit13** [comment]
I guess I'm a little confused about what you are asking for.  You will never get back the engine name indicated by the file extension if you use the default-engine setting.  default-engine overrides that for the entire file.

**Comment by PatrickMassot** [comment]
I'm sorry, I'm confusing. That's because I tried various things. Now I'm talking about what happens if you don't use the ``default-engine`` directive but rather rely on the file extension.

Steps to reproduce:
1) in ``plasTeX/Renderers/XHTML/`` rename ``Maths.zpts`` into ``Maths.pyts``
2) compile a LaTeX file containing some inline math and some display math.

Expected: all templates in the file should be interpreted as python string formatting, hence both kind of math should fail.

Actual result: only display math fails.

Explanation: inline math is the first template defined in that file and it gets the engine implied by file extension, hence fails. Then the ``engine`` options is wiped out and plasTeX default to ZPT hence the display math (and all other templates in that file) work.

Is that clearer?

**Comment by kesmit13** [comment]
Ok, I see now.  I added the copy that you requested.  The copy by itself wouldn't have worked except for the addition I made to the code earlier today because default-* options couldn't override keys that already existed in the options dictionary.  However, now that they can be applied as well if num_templates == 0, the copy is fine and fixes the issue you mention.

**Comment by kesmit13** [comment]
BTW, I pushed that change.

**Comment by PatrickMassot** [comment]
Thank you very much.
