### ISSUE TITLE
Html5

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#26]
Are there any short term plans to add an Html5 renderer? I mean a renderer that would output html5+css3 of course, but also use [MathJax](https://github.com/mathjax/MathJax) (or [KaTeX](https://github.com/Khan/KaTeX) maybe).

I'm about to start writing some math lecture notes using PlasTeX and Html5 is an absolute requirement. I'm willing to try writing the renderer (mostly templates actually) but I don't want to duplicate efforts if someone is already working on it (or has already done it somewhere).

**Comment by kesmit13** [comment]
We don't have any plans at the moment, but it certainly would be appreciated.  You could probably use most of XHTML and just extend it.  Tim may want to jump in here since he's done quite a bit of work with MathJax.  He might have implemented part of this somewhere.

**Comment by tiarno** [comment]
The way I handle math is to iterate over the html,  replacing any image with class=math (and alt text as a latex) with with svg and mathspeak text. You can get that output from the mathjax server (a nodejs server that listens for latex and outputs svg, mathml, and/or mathspeak.

In my opinion, to make that part of the plastex distribution would make it too complex and bloated for its main mission: creating a DOM from a LaTeX document. For example, I actually create DocBook XML with plasTeX and get HTML5 from that using the conventional docbook stylesheets.

The mathjax server is here: https://github.com/tiarno/mathjax-server
A recent presentation (15 min video) on the process is here:

http://youtu.be/_tYVqcdqcBM

**Comment by PatrickMassot** [comment]
Thank you very much for your comment. What I was thinking about when writing "MathJax" was the easier thing of simply keeping the math inside the html and let MathJax work on client side, using a page layout which load its javascript. Server side MathJax is something different and I understand that it is heavier, although plasTeX already calls external tools to convert TeX to images. 

At least in the beginning, I'll try to write templates outputting html5 and not touching math, together with a default page layout loading MathJax from their CDN. This keeps open the possibility of running author-side TeX to MathML conversion using MathJax in a second step.

I'm curious about the mathspeak part of your talk. Are there any free software reading math like this and running on Linux?

This is not the reason I'm currently investigating plasTeX but I did my PhD with a blind mathematician and I'm still curious about ways he could use new technologies (he currently either listen to human audio recording or read TeX sources).

**Comment by pkra** [comment]
If I may step in, @tiarno's mathjax-server depends on https://github.com/mathjax/mathjax-node which in turn can use https://github.com/zorkow/speech-rule-engine/ for speech-text generation; SRE implements mathspeak and ChromeVox speech rules, at varying verbosity settings.

**Comment by PatrickMassot** [comment]
@pkra Thanks. It looks very promising. However, the first thing I tried gives unexpected results. If you know this tool, can you explain the following:
```
$ node
> sre = require('speech-rule-engine');
> sre.toSpeech('<math><msup><mn>2</mn><mn>3</mn></msup></math>')
'23'
```
I would expect to get something like '2 sup 3' or '2 cubed'.

**Comment by pkra** [comment]
I think that's correct for mathspeak rules (which have some strange traditions). @zorkow will know better. You can try other rulesets. (This is getting off-topic though.)

**Comment by zorkow** [comment]
@PatrickMassot The result you see is expected, as you have not supplied the sre with a rule set to use yet. So it defaults to the original ChromeVox set that uses prosody (a change in pitch) to indicate superscript, which does not come out at all in the text string.

You need to set up the engine with an appropriate rule set first. E.g.,

```JavaScript
sre.setupEngine({semantics: true})
```

You should then see the result 
```JavaScript
> sre.toSpeech('<math><msup><mn>2</mn><mn>3</mn></msup></math>');
'two cubed'
```
If you want to use mathspeak rules, supply them as:

```JavaScript
 sre.setupEngine({semantics: true, domain: "mathspeak"})
```

The result will then be:

```JavaScript
> sre.toSpeech('<math><msup><mn>2</mn><mn>3</mn></msup></math>');
'2 cubed'
```

For more details how to setup the engine, have a look at the
[speech-rule-engine](https://github.com/zorkow/speech-rule-engine) github pages.

**Comment by pkra** [comment]
(Thanks for correcting me, @zorkow!)

**Comment by PatrickMassot** [comment]
Thanks @zorkow. It's awesome. I did look at speech-rule-engine's page but didn't understand the meaning of "swich on semantic interpretation". I also tried to figure out what would be the alternative to 'brief' style, with no success. I understand all this is work in progress and I guess the documentation is not yet targeting clueless users. You're doing very important work for blind people, keep going.

**Comment by zorkow** [comment]
I know. Better documentation is very much necessary, but somehow there's never the time for it. But I will try to explain at least the different rule sets and styles for the upcoming release of the [MathJax accessibility extension](https://github.com/mathjax/MathJax-a11y).
