### ISSUE TITLE
newcounter "the*" bug

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#28]
It seems that the `newcounter` class is broken when the name of the counter starts with "the". For instance try:

``` LaTeX
\documentclass{article}

\newcounter{theorem}

\begin{document}
\refstepcounter{theorem}
\thetheorem
\end{document}
```

LaTeX has no problem but plasTeX issues a warning `WARNING: unrecognized command/environment: theorem` and fails to output anything in xhtml rendering. The same code with a counter name that doesn't starts with "the" works ok.

**Comment by kesmit13** [comment]
This appears to be fixed now.  Let me know if you see otherwise.

**Comment by PatrickMassot** [comment]
It works for me. Thanks!
