### ISSUE TITLE
Renderer configuration

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#31]
Is there any way for a renderer to define config options (command line or config file)?

If no, would you be interested in a pull request where the function ``main`` in ``plastex`` asks all renderers for config options they'd like to declare, each in its own section of the ``ConfigManager`` object?

**Comment by kesmit13** [comment]
That's something we had planned a long time ago, but just never got around to.  I'd be interested in seeing what you had in mind.
