### ISSUE TITLE
Unrecognized command "\the\year"

### ISSUE THREAD

**Issue by mdk73** [tiarno/plastex#38]
plasTex does not recognize the command "\the\year", though LaTex does.

My test code:

``` LaTex
\documentclass[a4paper,10pt,fleqn, twoside]{book}
\setlength{\textwidth}{15cm}
\setlength{\textheight}{23.5cm}
\setlength{\evensidemargin}{0cm}

%according Plastex reference section 4.1
\newif\ifplastex
\plastexfalse

\usepackage[bookmarks=true]{hyperref}

\ifplastex
%do nothing
\else
\hypersetup{
    unicode=true,          % non-Latin characters in Acrobat’s bookmarks
    pdffitwindow=false,     % window fit to page when opened
    pdfstartview={FitV},    % fits the height of the page to the window
    colorlinks=true,       % false: boxed links; true: colored links
    linkcolor=blue,          % color of internal links
    citecolor=green,        % color of links to bibliography
    filecolor=blue,      % color of file links
    urlcolor=blue           % color of external links
}
\fi

\begin{document}

\chapter{Get the current Year}
Today is \today.\\
The current year is \the\year{}.

\end{document}
```

Shell output:

```
C:\Users\krause\workspace\manualUSB_en\plastex_test\the_year>c:\python27\python.exe c:\python27\Scripts\plastex --index-
columns=1 "--title=test case" .\plastex_the_year.tex
plasTeX version 1.0
 ( c:\python27\lib\site-packages\plasTeX\Packages\book.pyc )....
 ( c:\python27\lib\site-packages\plasTeX\Packages\hyperref.pyc ).....
WARNING: unrecognized command/environment: the
WARNING: Missing number in ./plastex_the_year.tex on line 31, treating as
   `0`. (.)
..
INFO: Directing output files to directory: plastex_the_year.
INFO: Importing templates from c:\python27\lib\site-
   packages\plasTeX\Renderers\PageTemplate
INFO: Importing templates from c:\python27\lib\site-
   packages\plasTeX\Renderers\XHTML
INFO: Importing templates from c:\python27\lib\site-
   packages\plasTeX\Renderers\XHTML\Themes\default
INFO: Using the imager "dvipng".
 [ index.html [ sect0001.html
WARNING: Using default renderer for the
WARNING: Using default renderer for year
```

A PDF-File (with the current year printed) and a zip-file with the plastex output (without the current year) is attached.
[plastex_the_year.zip](https://github.com/tiarno/plastex/files/401278/plastex_the_year.zip)
[plastex_the_year.pdf](https://github.com/tiarno/plastex/files/401280/plastex_the_year.pdf)

**Comment by PatrickMassot** [comment]
It seems that ``\the`` is not implemented by plasTeX. This is a fairly complex TeX command so I wouldn't try to improvise an implementation. 

Until one of the plasTeX experts give a proper answer you can use the following workaround (which is fairly generic). In your working directory create files:

year.sty
```LaTeX
\newcommand{\Year}{\the\year{}}
```

year.py
```python
from datetime import datetime

from plasTeX import Command
from plasTeX.Tokenizer import Token

class Year(Command):
    def invoke(self, tex):
        return [Token(datetime.now().year)]
```

Then in your TeX file ``\usepackage{year}`` and replace ``\the\year{}`` by ``\Year``. Run LaTeX as usual if you want a pdf. Tell plasTeX to look for packages in the current directory by setting the PYTHONPATH environment variable. For instance , if you use bash, replace 
```bash
plastex myfile.tex
```
by
 ```bash
PYTHONPATH=. plastex myfile.tex
```
Here the key is that plasTeX first looks for a python implementation of any given package before looking for a TeX implementation.

**Comment by mdk73** [comment]
Thanks for the detailed description.

Your workaraound is very nice. 
For me it has a critical drawback: It works only in the patched environments (both latex and python). 
I consider this hard to maintain, if different workstations are used with the same code. Each environment would need these patches...

My suggestion is either to implement the "/the" command (if possible ...) or to close this issue (e.g. if the effort for implementation is simply too much).

**Comment by kesmit13** [comment]
Simple support for the \the macro has been added.  It currently only resolves \year, \month, and \day.  If others are needed, let me know.
