### ISSUE TITLE
Preventing character substitution

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#45]
In ``plasTeX/__init__.py`` there is a list ``charsubs`` of "Character sequences that should be replaced by unicode". Under what circumstances is this list used? It sometimes get into my way but it's not easy to predict.

For instance try putting into ``test.tex`` the only line
```tex
\draw (0,0) -- (1,1) decorate { -- (2,1) } -- (3,0);
```
which could be part of a valid tikzpicture. Of course there is no hope for plasTeX to parse the original pgf/tikz package. The only thing I want plasTeX to do is to expand macros before passing the TeX source to pdflatex and pdf2svg and then include the resulting svg file into my html file.
See e.g. http://www.math.polytechnique.fr/perso/massot.patrick/enseignement/mat553/sect0023.html for a page produced by plasTeX using this strategy.

But the second  --  gets mangled to a unicode dash because of line 803 in the file mentioned above. Not the first one and not the third one, only the one inside the ``bgroup``:
```python
In [1]: from plasTeX.TeX import TeX

In [2]: doc=TeX(file='test.tex').parse()
WARNING: unrecognized command/environment: draw

In [3]: doc.childNodes[7:9]
Out[3]: [-, -]

In [4]: doc.getElementsByTagName('bgroup')[0].childNodes
Out[4]: [u' \u2013 (2,1) ']
```

So questions are:
* what is the rule deciding whether these character substitutions occur?
* is there any way I can tell plasTeX that it shouldn't not do that inside a tikzpicture environment say?

Right now I'm using a version of plasTeX where the offending line 803 is commented out but this is not a good workaround.

**Comment by kesmit13** [comment]
The best way to fix this would be to implement the tikzpicture package and put it in the plasTeX/Packages/ directory.  You don't have to actually implement all of the macros in that environment, but you do need to put placeholders in for them so that plasTeX won't complain about them.  

Then you override the normalize method to prevent it from using the character substitutions.  The class would look something like the following.  Let me know if this works out for you.  It is one of those edge cases that isn't that common.

class tikzpicture(Environment):

    class draw(Command):
        pass

    def normalize(self, charsubs=[]):
        """ Normalize, but don't allow character substitutions """
        return Environment.normalize(self)

**Comment by PatrickMassot** [comment]
Implementing a stub tikz package is already what I did to achieve the result, only needing to comment out that line about ``--``. 

The problem is that, in my example, the ``normalize`` method that causes trouble is called by a ``bgroup`` object, not a ``tikzpicture`` or ``draw`` object. I need a way to tell plasTeX to remember it is currently processing a ``tikzpicture`` environment during the whole digestion process of this environment. I guess there should be something like a context flag.

**Comment by kesmit13** [comment]
I wonder if inheriting from Verbatim would work in this case?

**Comment by PatrickMassot** [comment]
I guess that would stop macro expansion. Maybe I need to describe my setup more completely. Without the character substitution issue, the following works (again see the link in the first message of this thread for example output):
* my HTML5 renderer ``processFileContent`` method  checks ``userdata['processFileContents']`` to get a list of functions to apply to each page 
* my ``tikzpicture`` template inserts a ``tikzpicture`` tag containing only the output of the source method of the tikzpicture environment, i.e. it contains (using Jinja2 template engine) 
```html
<tikzpicture id="{{ obj.id }}">
{{ obj.source }}
</tikzpicture>
```

* my ``tikz.py`` function ``ProcessOptions`` adds a function ``tikzConvert`` to ``userdata['processFileContents']`` which searches for ``<tikzpicture> ... </tikzpicture>`` in the html output 
* for each tikzpicture tag, ``tikzConvert`` puts the content into a temporary TeX file using the  ``standalone`` document class 
* xelatex converts this temporary TeX file to a pdf file containing only the cropped picture
* the pdf is then converted using the ``pdf2svg`` program and the resulting svg object replaces the tikzpicture tag in the final html.

Now the issue with the ``Verbatim`` subclass idea is that xelatex wouldn't know about macros defined in the main file and used inside a tikzpicture environment.

Side remark: the workflow described above is probably not what you like but I was unable to understand plasTeX imagers API enough to use it.

**Comment by kesmit13** [comment]
It sounds like the correct way to fix this would be to create a charsubs stack on the ownerDocument.  That would be fairly invasive.  I wonder what would happen if you just cheated and set the ownerDocument.charsubs to an empty list at the begin environment and restored it at the end environment.  It's not pretty, but I think it would work.

**Comment by PatrickMassot** [comment]
Thanks for your help. I added to ``plasTeX/__init__py``:
```python
class NoCharSubEnvironment(Environment):
    """
    A subclass of Environment which prevents character substitution inside
    itself.
    """
    def __init__(self, *args, **kwargs):
        # Will hold the owner document charsubs to restore it at the end
        self.charsubs = []
        super(NoCharSubEnvironment, self).__init__(*args, **kwargs)

    def invoke(self, tex):
        # The goal is to prevent any character substitution while handling a
        # this environment.
        doc = self.ownerDocument
        if self.macroMode == Macro.MODE_BEGIN:
            self.charsubs = doc.charsubs
            doc.charsubs = []
        elif self.macroMode == Macro.MODE_END:
            doc.charsubs = self.charsubs
        super(NoCharSubEnvironment, self).invoke(tex)
```

and made my ``tikzpicture`` and ``tikzcd`` inherit from that class instead of ``Environment``. It seems to work.

However I'm still puzzled by that dash substitution thing (using your master branch, not my branch). Could you try to invoke plastex (without any command line flag of config file) on
```tex
\documentclass{article}

\begin{document}
Test -- dash. More {--} dash.
\end{document}
```
Here only the second -- gets replaced by a –

**Comment by kesmit13** [comment]
This appears to be an issue with the paragraph grouping code.  The 'document' environment will only create paragraphs if there is a blank line after the \begin{document}.  It's the paragraphs that convert two-dashes into a single character.  It's possible to force paragraphs in an environment by setting a class variable forcePars=True.  It did work in this simple test case, but I'm not sure what else this might affect.

**Comment by anteprandium** [comment]
@PatrickMassot I am very much interested in the very same idea of processing `tikzpicture` environments, would you share the code? Thx.

**Comment by PatrickMassot** [comment]
@anteprandium See [this class](https://github.com/PatrickMassot/plastex/blob/ebb61c52ad73b96ed7c22b2b9955f5a68db3f2f5/plasTeX/__init__.py#L917) and [this file](https://github.com/PatrickMassot/plastex/blob/ebb61c52ad73b96ed7c22b2b9955f5a68db3f2f5/plasTeX/Packages/tikz.py). Same comment as in #46: this is not yet ready for PR, use at your own risk.

**Comment by anteprandium** [comment]
@PatrickMassot Thanks a lot! For the time being, and while you have the time to polish it, I'll be ripping your tikz.py and related stuff. Thanks again!

**Comment by PatrickMassot** [comment]
I forgot to say this will work only with a renderer that uses ``userdata['processFileContents']`` as in [these lines](https://github.com/PatrickMassot/plastex/blob/ebb61c52ad73b96ed7c22b2b9955f5a68db3f2f5/plasTeX/Renderers/HTML5/__init__.py#L38-L39).
