### ISSUE TITLE
Variable tag names in templates

### ISSUE THREAD

**Issue by kskyten** [tiarno/plastex#49]
Is it possible to name an XML tag according to the node being rendered? Currently
I have pretty repetitive templating code that looks like this
```
name: example
<example tal:attributes="xml:id self/id">
<statement tal:content="self"></statement>
</example>

name: definition
<definition tal:attributes="xml:id self/id">
<statement tal:content="self"></statement>
</definition>
```
I would like something more like
```
name: example definition
<$node.nodeName tal:attributes="xml:id self/id">
<statement tal:content="self"></statement>
</$node.nodeName>
```
I tried to do
```
name: example
<string: $self.nodeName tal:attributes="xml:id self/id">
<statement tal:content="self"></statement>
</string: $self.nodeName>
```
but it didn't work.

Is this possible with ZPT templates or do I need to use another templating engine?

**Comment by PatrickMassot** [comment]
I would recommend switching to Jinja2, unless you spend so much time using ZPT or a similar templating engine for other projects that it would be a pain to switch to anything else. As far as I understand, using something like ZPT makes sense only if you absolutely need a web browser (or xml parser) to be able to swallow it. This is why javascript frameworks like AngularJS or VueJS use such horrors. They need the browser to be able to ignore all their custom tags before having javascript creating the actual content of the page. Here we have no such constraint. But again, if you do write AngularJS all day long and have plasTeX as a side project, then it makes sense to use ZPT to prevent constant mindset switch.

I think you should also have a look at the discussion in #46 which may be relevant.

**Comment by kskyten** [comment]
Ok, thanks. I will switch to Jinja.

**Comment by PatrickMassot** [comment]
Note something useful but not documented (my mistake): when developing Jinja2 templates, you can put in your template ``{{ debug() }}``. Each time plasTeX will try using this template, it will drop you into a python debugger (ipdb or pdb if ipdb is not available). Then type something like 
```python
obj = context['obj']
obj.id
obj.source
```
etc. to explore what your template is currently trying to render.
