### ISSUE TITLE
How to use plastex as tokenizer

### ISSUE THREAD

**Issue by da03** [tiarno/plastex#64]
I'm working on tokenizing latex, e.g.: given an input 
```
\begin{document}\begin{tabular}{ccc}$\sin x$&1&1\\\end{tabular}\end{document}
```
, I want to get the tokenized version 
```
\begin{document} \begin{tabular} { c c c } $ \sin x $ & 1 & 1 \\ \end{tabular} \end{document}
```

where the output is also able to compile. But when I use `tex = TeX().input(input); print ([token for token in tex.itertokens()]`, I get `\begin { d o c u m e n t...`, which apparantly does not compile. Is there a function for my purpose? Or is there a `detokenizer` which can take such a `\begin { d o c u m e n t}` and returns `\begin{document}`?

Any help is appreciated. Thanks in advance!

**Comment by kesmit13** [comment]
It needs to be a complete document, so you need a \documentclass{...} macro at the top.
