### ISSUE TITLE
Node equality

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#67]
I don't understand when two nodes are meant to be equal. This is checked in the test suite in [this test](https://github.com/tiarno/plastex/blob/9ec9de6fd733fd489e0fe7302b7832bca4d8a015/unittests/DOM/Node.py#L515-L522). But, as far as I can tell, it calls
```python
    def isEqualNode(self, other):
        """ Is this node equivalent to `other`? """
        return other == self
```
which seems to let python figure out what we mean. As you may have guessed already, this doesn't work anymore in python 3. So this test fails. I'm tempted to add a ``Node.__eq__`` method which looks like:
```python3
    def __eq__(self, other):
        try:
            return (self.nodeName == other.nodeName and
                    self.attributes == other.attributes and
                    self.childNodes == other.childNodes)
        except:
            return False
```
Maybe one would like to also add ``self.ownerDocument is other.ownerDocument`` or ``self.parentNode is other.parentNode``. Here we cannot use ``==`` instead of ``is`` since this would lead to infinite recursion.

Any thought on this?

**Comment by kesmit13** [comment]
It does make me wonder what Python 2 did.  All of those methods were added for completeness with the XML DOM specification.  Your suggestion seems like the right thing to do.  I don't think we need to check the owner or parent though.  As long as the content is the same, that seems appropriate.

**Comment by PatrickMassot** [comment]
Hum... with ``__eq__`` comes ``__hash__`` in python3. And nodes do occur as dict keys, e.g on [this line](https://github.com/tiarno/plastex/blob/9ec9de6fd733fd489e0fe7302b7832bca4d8a015/plasTeX/Renderers/__init__.py#L315). Again, I don't know what python 2 uses here. We could go with
```python
    def __hash__(self):
        return hash((self.nodeName, self.attributes, self.childNodes))
```
but it could turn out to be expensive (calling hash on all childNodes) so I'd like to know whether python2 actually does that.

**Comment by PatrickMassot** [comment]
The suggestion above was stupid: ``self.childNodes`` is a list, hence not hashable. Maybe python 2 simply does the equivalent of:
```python
def __hash__(self):
    return id(self)
```

**Comment by PatrickMassot** [comment]
Using the above ``__hash__`` using ``id``, I'm down to one failing test in python 3 (``testCaptionNodes`` in ``Packages/Longtable``), 160 passed. But it's bedtime.
