### ISSUE TITLE
Broken test for longtable

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#68]
The last python3-failing test actually fails with python 2 as well. [This test](https://github.com/tiarno/plastex/blob/f8e352d566f8fe8c8cc9002cd2a2d6c3855af767/unittests/Packages/Longtable.py#L148-L176) is broken and I think it has been broken since bf617991bf9df0 (two weeks after writing the test...). That commit puts the caption node inside the table title attribute where ``document.getElementsByTagName`` doesn't find it.

I guess I could easily rewrite this test but I'd like to read @kesmit13 thoughts about this first.

**Comment by kesmit13** [comment]
It looks like you are correct.  That test should be updated with the new attribute name.

**Comment by PatrickMassot** [comment]
Fixed in merged PR #69
