### ISSUE TITLE
References are not showing up correctly

### ISSUE THREAD

**Issue by robfelty** [tiarno/plastex#7]
I have noticed recently that references are not showing up correctly. For this minimal document:
\documentclass{article}
\begin{document}
hello world. See figure \ref{F:foo}
\begin{figure}[b]
foo
\caption{foo is bar}
\label{F:foo}
\end{figure}
\end{document}

I get this output:

<div><p>hello world. See figure <a href="index.html#F:foo">#.#.#</a> </p><div id="F:foo" class="figure"><p> foo </p><div class="caption"><b> </b>: <span>foo is bar</span></div></div></div>

Note the #.#.#, instead of something like Figure 1.

I have tried this using both plastex 0.9.1 and 1.0, with TexLive 2012, on Fedora 21

I tried recompiling a document I created a year ago, which did not have this problem, and I experience it now as well. This is the output I get when running PlasTeX;
robert_felty$ plastex foo
plasTeX version 0.9.1
ERROR: Could not load package "article": name 'Command' is not defined
..
WARNING: unrecognized command/environment: thefigure
WARNING: unrecognized command/environment: figurename
INFO: Directing output files to directory: foo.
INFO: Importing templates from /usr/lib/python2.7/site-
   packages/plasTeX/Renderers/PageTemplate
INFO: Importing templates from /usr/lib/python2.7/site-
   packages/plasTeX/Renderers/XHTML
INFO: Importing templates from /usr/lib/python2.7/site-
   packages/plasTeX/Renderers/XHTML/Themes/default
INFO: Using the imager "dvipng".
 [ index.html ]

**Comment by robfelty** [comment]
I think I figured it out actually. I had figured it out a year ago, but then my changes had gotten overwritten. 
See this article for a fix:
http://robfelty.com/2013/01/17/small-fix-for-article-class-in-plastex

**Comment by tiarno** [comment]
When I run python2.7, plasTeX 1.0, I run against your example and the figure numbers are correct.

    lib/python2.7/site-
       packages/plasTeX/Packages/article.pyc
     )
    INFO: Directing output files to directory: test.
    INFO: Importing templates from /Users/tim/anaconda/envs/py27/lib/python2.7
       /site-packages/plasTeX/Renderers/PageTemplate
    INFO: Importing templates from /Users/tim/anaconda/envs/py27/lib/python2.7
       /site-packages/plasTeX/Renderers/XHTML
    INFO: Importing templates from /Users/tim/anaconda/envs/py27/lib/python2.7
       /site-packages/plasTeX/Renderers/XHTML/Themes/default
    INFO: Using the imager "dvipng".
     [ index.html ]

I don't understand your last message--is this still a bug or is something different in your local distribution?

**Comment by tiarno** [comment]
cannot reproduce issue.
