### ISSUE TITLE
Filename generation reset

### ISSUE THREAD

**Issue by PatrickMassot** [tiarno/plastex#77]
Output file names generation is driving me crazy. When I try to render two documents in the same python script then it seems available filenames are not reset, although I recreate *all* objects. Say I have inside ``/tmp/test.py``:
```python
import os
from plasTeX.TeX import TeX, TeXDocument
from plasTeX.Config import config
from plasTeX.Renderers.XHTML import Renderer

cur_dir = os.getcwd()
try:
    os.makedirs('build')
except:
    pass

doc = TeXDocument(config=config)
tex = TeX(doc)
tex.input("\\documentclass{article}\\begin{document}Hello.\\end{document}")
doc = tex.parse()
doc.userdata['working-dir'] = '.'

renderer = Renderer()
os.chdir('build')
renderer.render(doc)

os.chdir(cur_dir)
try:
    os.makedirs('build2')
except:
    pass
doc = TeXDocument(config=config)
tex = TeX(doc)
tex.input("\\documentclass{article}\\begin{document}Hello.\\end{document}")
doc = tex.parse()
doc.userdata['working-dir'] = '.'

renderer = Renderer()
os.chdir('build2')
renderer.render(doc)
```
The first rendering renders to ``build/index.html`` but the second one renders to ``build2/sect0001.html``!!!

I don't understand what I'm doing wrong but it is a huge problem when writing unittests. I need my tests to be isolated from each other but, whatever I do, some devil remembers I already rendered some ``index.html``. I tried using ``deepcopy`` everywhere, using ``del`` after using every objects but nothing worked.

**Comment by kesmit13** [comment]
That's strange.  Filenames are generated by the Filenames generator in the render method of a renderer.  Each time you call render, it should create a new instance of that filename generator in the self.newFilename property of that renderer.

I will admit that multiple rendering is a little ugly because the renderer attaches itself to the Node class during the run, but the following render call should whack that attribute with the new renderer instance.

**Comment by PatrickMassot** [comment]
This is much weirder than multiple rendering. In my example the document object is recreated from scratch. I don't see how there could be remnants of the mixin procedure. Did you try my example? Can you reproduce this problem?

**Comment by PatrickMassot** [comment]
This is so sad. I've been doing rather serious python for more than two years and I still waste one afternoon not seeing The Bug. I can still read, in `plasTeX/Filenames.py``:
```python
class Filenames(object):

    def __init__(self, spec, charsub=[], vars={}, extension='', invalid={}):
```
and fail to jump to fixing the bug without even trying to understand what this object is meant to do. I need to buy an A0 printer to produce a poster saying: "Thou shalt not use mutable default values".

**Comment by kesmit13** [comment]
That was written a very long time ago.  Likely before about the dangers of mutable objects in function definitions was more commonly known.  Apparently, you're the first person to trip over it.  :)

**Comment by PatrickMassot** [comment]
I'm not complaining about what you wrote, I'm blaming me for the time it took me to understand the problem. To be honest I lost time thinking I had a problem with the way I handled pytest fixtures. Anyway, I'll fix this right away.

**Comment by kesmit13** [comment]
It's one of those subtle ones that when you assume that the code has been working "properly" all these years, how could it possibly be wrong?

**Comment by PatrickMassot** [comment]
I think part of the problem is that it is indeed rather hard to use plasTeX without using the main script ``plasTeX/plastex``. There are too many things done in this script. It's not the first time I notice it makes it difficult to write tests. Actually you can see it in your ``unittests/FunctionalTests.py`` which uses ``subprocess.Popen`` to use plasTeX!

**Comment by niklasp** [comment]
How did you go about it? I am also trying to use python without the main script @PatrickMassot . Also, I do not want to write any configuration values in LaTeX. I have opend #100 , maybe you can help out?

**Comment by PatrickMassot** [comment]
Fixing the mutable default value fixed this issue, this is how I went about it. It is still hard to use plasTeX as a lib rather than the main script. Improving that would require quite a lot of changes and, as far as I can see, no one has enough motivation and time for this. I'm not using plasTeX currently and I have developments  I've wanted to polish and merge in for almost one year. 

Currently there are quite large efforts aiming to use plasTeX in unconventional ways in the context of the stacks project, see http://pbelmans.ncag.info/blog/2017/08/27/introduction-gerby-plastex/ There may be ideas to get there.

**Comment by niklasp** [comment]
@PatrickMassot How is the status of your testing? Do all tests pass? I am currently having problems to get the longtable tests run. Can you affirm that?

**Comment by PatrickMassot** [comment]
@niklasp I had no problem with tests, except what I explicitly mentionned in #70 and #71 before you pushed 10f51da083851247954aaabc0ad8d540e763c290. Now with my PR #102 I can run all tests locally. But I just saw Travis is in trouble. I'll try to investigate.
