### ISSUE TITLE
TeX primitive mathchardef not defined

### ISSUE THREAD

**Issue by axlmad79** [tiarno/plastex#8]
Hi,

I recently started using plasTeX. I'm mainly interested in using it to parse complex LaTeX documents and then extract specific sections/environments to convert them to some other format. The first problem I've encountered is that \mathchardef primitive is not defined so I've prepared a small patch based on the way chardef is defined. If interested please, contact me to submit the patch or provide this minor enhacement yourself in a future version of the package. Thank you.

Best regards,
Alex

**Comment by tiarno** [comment]
hi, thanks. Could you provide a code-snippet or even better, a pull request? 
thanks,
--Tim

**Comment by tiarno** [comment]
Thanks for the contribution Alex. I merged your pull request.
