### ISSUE TITLE
pip installs incompatible plastex to python3

### ISSUE THREAD

**Issue by sinisterdexter** [tiarno/plastex#86]
I installed plastex using "pip3 install plastex".

I'm using version 1.0 of plastex, judging from /usr/local/bin/plastex line 12:

`__version__ = '1.0'`

The first line identifies the python version being used:

`#!/usr/local/opt/python3/bin/python3.6`

Running this version of Python, I cannot import plasTeX:

```
Python 3.6.1 (default, Apr  4 2017, 09:36:47) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import plasTeX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/plasTeX/__init__.py", line 217
    raise AttributeError, 'could not find attribute "title"'
                        ^
SyntaxError: invalid syntax
```

I get a similar error when trying to run plasTeX from the command line:

```
$ plastex methods_and_results_second_draft.tex 
  File "/usr/local/bin/plastex", line 21
    except Exception, msg:
                    ^
SyntaxError: invalid syntax
```

I was confused by these problems since this syntax has been disallowed since Python 3.0, [according to this changelog](https://docs.python.org/3.0/whatsnew/2.6.html#pep-3110). Looking at [the plastex entry in the Python package index](https://pypi.python.org/pypi/plasTeX/1.0), I found that there's no python version specified. So my guess is that, since there's no version specified, pip will install an incompatible version of plastex, instead of stating that the package is not available for python 3.

**Comment by tiarno** [comment]
I understand what you're saying. There is an experimental branch on github, plastex3 if you want to play with it. As for the Pypi site, plasTeX was released before the Python version checking in pip existed.  The categories information on Pypi does say it is for Python2 only.
