### ISSUE TITLE
Error in documentclass{revtex4-1}

### ISSUE THREAD

**Issue by peterzjx** [tiarno/plastex#89]
So I am trying on a document starting with
`\documentclass{revtex4-1}
\usepackage{graphicx}
\usepackage{amsmath}`

plasTeX gives the following error: 

`  File "/usr/local/lib/python2.7/dist-packages/plasTeX-1.0-py2.7.egg/plasTeX/Renderers/XHTML/__init__.py", line 100, in doJavaHelpFiles
    latexdoc = document.getElementsByTagName('document')[0]
IndexError: list index out of range
`

I understand that plastex may not be able to support all those different document classes. I am wondering if there is a way to fix it? I am thinking that a patch in the Package directory might be the answer, but I don't know where to start. I hope someone could give me a hint on it.

**Comment by PatrickMassot** [comment]
There are at least two possible workarounds here. The first one is to copy the content of ``/usr/local/lib/python2.7/dist-packages/plasTeX-1.0-py2.7.egg/plasTeX/Packages/article.py`` into some ``revtex4-1.py`` contained either in the same directory if you want a system-wide workaround (probably not a very good idea) or in the directory where your tex file sits (or in some other directory that you would then add to the TEXINPUTS environment variable if this means something to you).

A more flexible solution would be to have two separate headers for ``pdflatex`` and ``plastex``. You could have in ``main.tex``:
```latex
\usepackage{amsmath}

\begin{document}
...
\end{document}
```
in ``print.tex``:
```latex
\documentclass{revtex4-1}
\input{main.tex}
```
and in ``web.tex``:

```latex
\documentclass{article}
\input{main.tex}
```
This way you can also have different versions of problematic macros (as a rule of thumb, this includes every macro which is so much tied to pdf output that it would make no sense for the html output).

If you are new to plasTeX, you may want to clone the latest version from github and try the HTML5 renderer, which, by default, will give you a more modern looking html output.

**Comment by peterzjx** [comment]
Thank you, Patrick!
Could you help me with a more general related problem? I'm trying to convert a bunch of latex source code downloaded from arxiv, which individually includes various packages. As a lot of them are not supposed to be supported, I always get error messages like this:
```
( /usr/local/lib/python2.7/dist-
   packages/plasTeX-1.0-py2.7.egg/plasTeX/Packages/amsmath.pyc
 ) ( /usr/share/texlive/texmf-dist/tex/latex/amsmath/amscd.sty
 ( /usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty )
ERROR: Error while expanding "csname" in /usr/share/texlive/texmf-
   dist/tex/latex/amsmath/amscd.sty on line 82 (sequence item 2: expected
   string or Unicode, string found)
WARNING: Error opening package "amscd.sty" ( sequence item 2: expected
   string or Unicode, string found )
```
Usually, after trying to load a sty file, it gets an error in expanding one of the commands. After some manual trying, I found at least 'xcolor', 'mathtools', 'dcolumn', 'ulem', 'slashed' and 'hyperref' are possible problematic packages. My question is, besides of changing the raw document, is there a way for me to fix it, or at least avoid loading the particular package and try to proceed?

**Comment by PatrickMassot** [comment]
Trying to convert a lot of tex files which were written without having plasTeX in mind is bound to be a difficult task. If you have time and python skills you can try to help implement more packages in plasTeX. For amscd you can adapt what I did for TikZ and tikz-cd in PR #81.

Otherwise you can still avoid trying to parse the original sty files by creating stub python versions (plasTeX will have try python versions first).

**Comment by peterzjx** [comment]
Thanks a lot for your help.

**Comment by kesmit13** [comment]
Patrick is correct.  Trying to interpret (La)TeX packages that are intended for printed output, but using them to generate something like HTML almost never works.  plasTeX can expand some simple to intermediate macros, but complex packages will always be beyond its capabilities.  

Using dummy Python packages of the same name (even if they are empty) can help you get past the parsing of the document at least.  Then you can implement the Python classes in each of those packages as needed.  An alternative method would be to write simplified LaTeX macros that render the way you want in plasTeX and conditionally include them using \ifplastex ... \fi type blocks.
